### PR TITLE
Portfolio_For_Desktop_Version

### PR DESCRIPTION
**Pull request by FaranoshAmini**
I created Portfolio for the desktop version :
--There is no linters error
--I used CSS grid and CSS flexbox

### CODE REVIEW

**Review by algerina — CHANGES_REQUESTED** [review]
Hi @FaranoshAmini , 

Great work so far 👏 
You've done well, but there are still some changes to do.

 ## Highlights
- Linters are passing
- Descriptive comments and pull request
- Your project looks awesome

 ## Required Changes ♻️
_Check the comments under the review._
[ ] Please align your social media icons on the about me section to match Figma design:
captures_chrome-capture-2022-5-4 (1)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._




Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @algerina in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by FaranoshAmini** [comment]
@algerina  Can you explain this, please?

**Comment by algerina** [comment]
> @algerina Can you explain this, please?

Of course, in the Figma design the social media icons are aligned to the left:

figma

On my browser, they were centered but now I can see that they are aligned properly.

**Comment by FaranoshAmini** [comment]
> > @algerina Can you explain this, please?
> 
> Of course, in the Figma design the social media icons are aligned to the left:
> 
> figma
> 
> On my browser, they were centered but now I can see that they are aligned properly. Just resubmit again please.

@algerina  Thank you so much.

**Review by aimemalaika — APPROVED** [review]
Hi @FaranoshAmini , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
